export function hexdump(bytes: Uint8Array, addr = 0, length = bytes.byteLength) {
    const end = addr + length
    while (addr < end) {
        let line = addr.toString(16).padStart(4, "0")
        for (let i = 0, j = addr; i < 16 && j < end; ++i, ++j) {
            line += " " + bytes[j].toString(16).padStart(2, "0")
        }
        line = line.padEnd(4 + 16 * 3 + 1, " ")
        for (let i = 0, j = addr; i < 16 && j < end; ++i, ++j) {
            const b = bytes[j]
            if (b >= 32 && b < 127) {
                line += String.fromCharCode(b)
            } else {
                line += "."
            }
        }
        addr += 16
        console.log(line)
    }
}

// convert the dump generated by hexdump()
export function parseHexDump(data: string): Uint8Array {
    const rows = data.trim().split(/\r?\n/)
    let vec: number[] = []
    for (let i = 0; i < rows.length; ++i) {
        const row = rows[i].trim()
        if (row.length === 0) {
            continue
        }
        for (let j = 0; j < 16; ++j) {
            let n: number
            let idx = j * 3 + 5
            n = parseInt(row.substring(idx, idx + 2), 16)
            if (isNaN(n))
                break
            vec.push(n)
        }
    }
    return new Uint8Array(vec)
}